{{- $fullName := include "server.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ .Values.ingress.type }}-{{ $fullName }}-production
  labels:
    {{- include "server.labels" . | nindent 4 }}
  annotations:
{{- if eq Values.ingress.type "agic" -}}
      kubernetes.io/ingress.class: azure/application-gateway
{{- else -}}
      kubernetes.io/ingress.class: nginx
{{- end }}
spec:
  rules:
  - host: {{ .Values.ingress.hostName }}
    http:
      paths:
      - backend:
          serviceName: {{ $fullName }}-production
          servicePort: {{ $svcPort }}
