{{- if .Values.ingress.enabled -}}
{{- $fullName := include "server.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: nginx-{{ $fullName }}-staging
  labels:
    {{- include "server.labels" . | nindent 4 }}
  annotations:
      kubernetes.io/ingress.class: nginx

spec:
  rules:
  - host: staging.{{ .Values.ingress.nginx.hostName }}
    http:
      paths:
      - backend:
          serviceName: {{ $fullName }}-staging
          servicePort: {{ $svcPort }}
{{- end }}
